# Generated by Django 3.2.7 on 2021-09-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210927_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_profile',
        ),
    ]
