# Generated by Django 3.2.7 on 2021-10-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211014_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
    ]
